web:
  addr: 127.0.0.1:8080
  domain: localhost
mail:
  smtp: smtp.163.com
  port: 994
  user: example@163.com
  pass: example
database:
  user: root
  pass: nasjkdnfhbjasb
  server: tcp(127.0.0.1:3306)
  name: panel
  loc: Asia%2fShanghai
recaptcha: xxxxxxxxxxxxxxxxxxxxxxxx