version: "3.3"

services:
  caddy:
    image: abiosoft/caddy
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy/Caddyfile:/etc/Caddyfile
      - ./data/caddy/certs:/root/.caddy
      - ./nbdomain/theme/static/:/data/static/
      - ./data/nbdomain/upload/:/data/upload/
      - ./dashboard/:/data/dashboard/
  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: nbdomain
  nbdomain:
    depends_on:
      - caddy
      - mysql
    build: ./nbdomain
    restart: always
    volumes:
      - ./data/nbdomain:/data/data
